### ISSUE TITLE
Hello, could you help?

### ISSUE THREAD

**Issue by morfiusmatrix** [kydycode/chatgpt-3.5-turbo#1]
Hello, I've been looking at your code and trying to use gpt3 turbo, but I have an error of the following kind could you help "
Python\Python311\Lib\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-uvUHv8eC946TWR5Lmro33pXW on tokens per min. Limit: 40000.000000 / min. Current: 409600.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
"

if it is not difficult for you, could you help me in solving this problem. As I understand it, I configured everything correctly, the only thing left for me is to link a payment card and after that the problem will be solved?
I also attach my telegram @MoguBse

**Comment by vitalio-sh** [comment]
> Hello, I've been looking at your code and trying to use gpt3 turbo, but I have an error of the following kind could you help " Python\Python311\Lib\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line raise self.handle_error_response( openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-uvUHv8eC946TWR5Lmro33pXW on tokens per min. Limit: 40000.000000 / min. Current: 409600.000000 / min. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method. "
> 
> if it is not difficult for you, could you help me in solving this problem. As I understand it, I configured everything correctly, the only thing left for me is to link a payment card and after that the problem will be solved? I also attach my telegram @MoguBse

It looks like you've hit the rate limit for your OpenAI API key on the gpt-3.5-turbo model. According to the error message, your current usage is exceeding the rate limit of 40000 tokens per minute for this model.

You can contact OpenAI support at [support@openai.com](mailto:support@openai.com) to see if they can increase your rate limit or provide other solutions. Another option is to try using a different model that may have a higher rate limit, or to wait a while before trying again.

Additionally, the error message suggests that you can increase your rate limit by adding a payment method to your OpenAI account. You can do this by visiting https://platform.openai.com/account/billing and following the instructions there.

I hope this helps! Let me know if you have any other questions or issues.

**Comment by morfiusmatrix** [comment]
now I have a bot running on the text-davinci-003 model and I would like to upgrade it to the gpt-3.5-turbo model, but when changing only the name, it does not answer me anything, could you help with the adaptation or advise where to start and how to get around the limit? Because I am using a new key in which there were no requests, but it does not work. Here is the code itself "    
    completions = await openai.Completion.acreate(
            model="text-davinci-003",
            prompt=text,
            temperature=0.7,
            max_tokens=max_tokens,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0,
        )"

**Comment by morfiusmatrix** [comment]
Full error code when running your code
```
Traceback (most recent call last):
  File "F:\Работа\GPT\gpt3turbo\chatgpt-3.5-turbo-main\chatgpt-3.5-turbo-main\chatgpt-3.5-turbo\main.py", line 77, in <module>
    main()
  File "F:\Работа\GPT\gpt3turbo\chatgpt-3.5-turbo-main\chatgpt-3.5-turbo-main\chatgpt-3.5-turbo\main.py", line 48, in main
    response = send_message(message_log)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Работа\GPT\gpt3turbo\chatgpt-3.5-turbo-main\chatgpt-3.5-turbo-main\chatgpt-3.5-turbo\main.py", line 10, in send_message
    response = openai.Completion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\morfi\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\morfi\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\morfi\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\morfi\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\morfi\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: messages
```
